### ISSUE TITLE
RedeemCheck

### ISSUE THREAD

**Issue by HarpyWar** [MinterTeam/minter-php-sdk#50]
RedeemCheck does not work, or example is incorrect.

Firstly MinterTx->data->proof must be in hex instead of string, which is described in the example.
```php
$tx = new MinterTx([
    'nonce' => $nonce,
    'gasPrice' => 1,
    'gasCoin' => 'MNT',
    'type' => MinterRedeemCheckTx::TYPE,
    'data' => [
        'check' => $check_id,
        'proof' => str2hex($check_proof)
    ],
    'payload' => '',
    'serviceData' => '',
    'signatureType' => MinterTx::SIGNATURE_SINGLE_TYPE // or SIGNATURE_MULTI_TYPE
]);

$sign = $tx->sign($privateKey);
```
But even with correct tx data I receive the following error response:
```json
string(254) "{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": 412,
    "message": "Check tx error",
    "tx_result": {
      "code": 106,
      "log": "rlp: input string too short for [65]uint8, decoding into (transaction.RedeemCheckData).Proof"
    }
  }
}"
```

**Comment by GrKamil** [comment]
Hello, @HarpyWar.
In the data of MinterRedeemCheckTx you have two fields: check and proof.
1. check - it is the generated by SDK Minter check (starting from Mc...)
2. proof - generated by SDK proof. You don`t need to convert created proof to hex, because it is already hex string. Here you can see how to create proof for Minter check: https://github.com/MinterTeam/minter-php-sdk#example-17

**Comment by danil-lashin** [comment]
@HarpyWar it is not possible to redeem a check while the network is under load. At least for now. Gas price for this kind of transaction is fixed to 1 to prevent fraud.
